sudo: true
language: python
dist: trusty
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  - DJANGO=django111
  - DJANGO=django20
  - DJANGO=django21
before_install:
  - sudo apt-get update && sudo apt-get build-dep python-imaging
  - sudo service postgresql restart
install:
 - pip install tox
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
services:
  - postgresql
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension hstore"
  - psql -U postgres template1 -c "create extension citext"
  - psql -c 'create database model_mommy;' -U postgres
  - psql -c 'create database model_mommy_test;' -U postgres
script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{postgresql}
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-{sqlite}
